### ISSUE TITLE
feat: Add minimal WASM api

### ISSUE THREAD

**Issue by roninjin10** [evmts/tevm-monorepo#1040]
## Tasks

- [ ] Implement a single [`tevm.getAccount` action](https://github.com/evmts/tevm-monorepo/blob/main/packages/actions-types/src/handlers/GetAccountHandler.ts) in [@tevm/revm](https://github.com/evmts/tevm-monorepo/tree/main/experimental/revm) package.

What this looks like is a javascript function wrapping a revm implementation imported from the `@tevm/revm` package that has a function called `getAccount` that implements some subset of the [`getAccountHandler`](https://github.com/evmts/tevm-monorepo/blob/main/packages/actions-types/src/handlers/GetAccountHandler.ts) interface.  This interface takes an address and returns general account information like `balance`, `deployedBytecode`, and `nonce`. 

## Acceptance criteria

- Give the package is experimental and unused atm any contribution that makes progress even if not complete will be merged
- Implement 1 or more of the following properties in [GetAccountResult](https://github.com/evmts/tevm-monorepo/blob/main/packages/actions-types/src/result/GetAccountResult.ts)
- Likely easiest to start with echoing the address but feel free to implement more or all of them

## Description

Tevm is currently implemented purely is js with [ethereumjs](https://github.com/ethereumjs/ethereumjs-monorepo). We want to use [revm compiled to wasm](https://github.com/evmts/tevm-monorepo/tree/main/experimental/revm) to implement the same [MemoryClient api](https://github.com/evmts/tevm-monorepo/blob/main/packages/memory-client/src/MemoryClient.ts).

The most logical place to start is with the simplist action which is currently `getAccount`.

## Helpful examples

- The typescript type for the action is called [GetAccountHandler](https://github.com/evmts/tevm-monorepo/blob/main/packages/actions-types/src/handlers/GetAccountHandler.ts)
- There is an example of the ethereumjs version of the handler in [getAccountHandler.js](https://github.com/evmts/tevm-monorepo/blob/main/packages/actions/src/tevm/getAccountHandler.js). 
- Above example takes a [baseClient](https://github.com/evmts/tevm-monorepo/blob/main/packages/base-client/src/createBaseClient.js) as a param and returns a handler. This helps codesplitting. Don't worry about it looking exactly like this as we want to start simple.

## Follow up tasks

The following tasks will be unblocked after this task is closed

- [ ] Create an example using it in stackblitz with vite
- [ ] Write a playwright test for it
