### ISSUE TITLE
test: Add benchmark peformance tests to `@tevm/memory-client` package

### ISSUE THREAD

**Issue by roninjin10** [evmts/tevm-monorepo#945]
This is an medium size task but good for beginners

## Description

Tevm will very soon run up against peformance bottlenecks. To prepare for that we should add peformance tests so we can quickly improve them and prevent large regressions. Performance tests go in the `tests/bench/src` folder

## Tasks

- [ ] Add a computationally heavy benchmark test (rather than something that fetches a lot of state)
- [ ] Add a benchmark tests for `tevm_call` both for executing tx and not executing tx
- [ ] Add benchmark tests for `tevm_script`
- [ ] Add benchmark tests for `tevm_getAccount` and `tevm_setAccount`
- [ ] Add benchmark tests for `eth_getCode`
- [ ] Add benchmark test for `eth_getStorageAt`
- [ ] Add benchmark tests for `tevm_dumpState` and `tevm_loadState`

**Comment by roninjin10** [comment]
[The first benchmark test is added here](https://github.com/evmts/tevm-monorepo/pull/949). Will add a checklist to the repo of more tests we want

**Comment by roninjin10** [comment]
There are a good chunk of benchmark tests but later would be good to start adding them to smaller units
