### ISSUE TITLE
example: Update 1 or more of the example apps to use `@tevm/http-client` and/or `@tevm/memory-client`

### ISSUE THREAD

**Issue by roninjin10** [evmts/tevm-monorepo#946]
This is a series small sized task good for beginners. If you take this one of these on reach out if you get stuck.  

If you want to take one on comment which one you want and I will assign it to you via updating this comment

## Tasks

Most wanted updates
- [ ] [Update @tevm/example-vite](https://github.com/evmts/tevm-monorepo/pulls)
- [ ] [Update @tevm/example-bun](https://github.com/evmts/tevm-monorepo/pulls) (similar but outdated bun vm example exists here: https://github.com/evmts/EVMts-VM-example)
- [ ] ⏳ #952 @0xpolarzero

Nice to have

- [ ] ⏳ #953 @sreeragdas 
- [ ] Update @tevm/example-esbuild 
- [ ] Add a @tevm/example-remix project
- [ ] Add a @tevm/example-rspack project
- [ ] Add a @tevm/example-rollup project
- [ ] Add an example using @tevm/ethers
- [ ] Add an example using @tevm/viem

## Description

Currently there are many example apps in `examples` folder that were originally added before the Tevm ethereum clients existed. They use tevm for contracts but execute them using `ethers` `viem` or `wagmi`. 

We can keep the existing ethers/viem/wagmi code but we should also add simple components using the Tevm vm.

## Memory client

The easiest one to use is memory client. Initialize a memory client and make a simple UI that interacts with it using scripts.

## HttpClient

For the Next.js app consider using the @tevm/server package to run tevm in a serverless function and use a `http-client` to interact with it

## Existing examples

The bun repo has a vm example that is out of date using an older api: https://github.com/evmts/EVMts-VM-example
This pr is updating the vite example. This example is significantly more involved though than what we are asking for here: https://github.com/evmts/tevm-monorepo/pulls

**Comment by sreeragdas** [comment]
hi , can i work on this ?

**Comment by roninjin10** [comment]
Sure @sreeragdas ! Which one do you want to pick up?

**Comment by roninjin10** [comment]
> hi , can i work on this ?

Sure @sreeragdas ! Which one do you want to pick up?

**Comment by sreeragdas** [comment]
can i work on Update @tevm/example-esbuild .

**Comment by roninjin10** [comment]
@sreeragdas all yours https://github.com/evmts/tevm-monorepo/issues/953

Reach out if you need any help
