### ISSUE TITLE
Check jsdoc of action handlers for correctness (good first issue)

### ISSUE THREAD

**Issue by roninjin10** [evmts/tevm-monorepo#950]
This is a simple good first issue that is broken up into many tasks. Comment if you want to take on any specific task.

## Description

Jsdocs are comments above the code that are then generated into reference docs.

Tevm has jsdocs for nearly 100% of the api but they have never been checked for correctness. This issue is to simply go through the jsdocs and do following

- Validate the jsdoc has a good description of what it does. Add a description if it is missing
- Validate the example is up to date and works
- Validate that anything useful elsewhere in the docs that should be linked to has a link. Links can be added with markdown syntax

## Tasks

Comment if you want to take on any of the following list of apis. You only need to update the handler code which has a path in the docs. If you wish you can also:

- update the jsdocs for the specific handler in `@tevm/client-types`
- update the jsdocs for the matching JSON-RPC in `@tevm/procedures`

But this is not necessary.

- [ ] [blockNumberHandler](https://tevm.sh/reference/tevm/actions/functions/blocknumberhandler/) also [memory client](
- [ ] [callHandler](https://tevm.sh/reference/tevm/actions/functions/callhandler/)
- [ ] [chainIdHandler](https://tevm.sh/reference/tevm/actions/functions/chainidhandler/)
- [ ] [contractHandler](https://tevm.sh/reference/tevm/actions/functions/contracthandler/)
- [ ] [dumpStateHandler](https://tevm.sh/reference/tevm/actions/functions/dumpstatehandler/)
- [ ] [ethAccountsHandler](https://tevm.sh/reference/tevm/actions/functions/ethaccountshandler/)
- [ ] [ethCallHandler](https://tevm.sh/reference/tevm/actions/functions/ethcallhandler/)
- [ ] [ethSignHandler](https://tevm.sh/reference/tevm/actions/functions/ethsignhandler/)
- [ ] [ethSignTransactionHandler](https://tevm.sh/reference/tevm/actions/functions/ethsigntransactionhandler/)
- [ ] [gasPriceHandler](https://tevm.sh/reference/tevm/actions/functions/gaspricehandler/)
- [ ] [getAccountHandler](https://tevm.sh/reference/tevm/actions/functions/getaccounthandler/)
- [ ] [getBalanceHandler](https://tevm.sh/reference/tevm/actions/functions/getbalancehandler/)
- [ ] [getCodeHandler](https://tevm.sh/reference/tevm/actions/functions/getcodehandler/)
- [ ] [getStorageAtHandler](https://tevm.sh/reference/tevm/actions/functions/getstorageathandler/)
- [ ] [loadStateHandler](https://tevm.sh/reference/tevm/actions/functions/loadstatehandler/)
- [ ] [scriptHandler](https://tevm.sh/reference/tevm/actions/functions/scripthandler/)
- [ ] [setAccountHandler](https://tevm.sh/reference/tevm/actions/functions/setaccounthandler/)
- [ ] [traceCallHandler](https://tevm.sh/reference/tevm/actions/functions/tracecallhandler/)
